export class User {
  _id!:string
  fullname!:string
  email!:string
  image!:string
  firstJobDay!:any
  totalWorkTime!:string
  university!:string
  graduationTime!:string
  workTitle!:string
  createdAt!:any
  department!:string
  description!:string
  previousJob!:string
  previousWorkTitle!:string
  skills!:string
  position!:string
  __v!:string
  }
